// ===== ABC DEL TRADING — 12 Módulos de Contenido =====
const MODS=[
// ─── M1: Activos Básicos ───
{id:'m1',title:'¿Qué es un activo?',icon:'fi-sr-box-open-full',xp:40,steps:[
{type:'act',icon:'fi-sr-box-open-full',ic:'orange',title:'¿Qué es un activo?',
 desc:'Un activo es algo que tiene valor y puedes comprar o vender. ¿Cuál de estos es un activo financiero?',
 ch:[{t:'Una acción de Apple',k:'A',ok:true},{t:'Tu mascota',k:'B',ok:false},{t:'Una idea',k:'C',ok:false}],
 exp:{t:'Todo lo que tiene valor en el mercado',p:'Acciones, criptomonedas, divisas, oro — todo eso son activos financieros. Son las "piezas" que compras y vendes en trading.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'orange',title:'¿Verdadero o Falso?',
 desc:'Un ETF es un fondo que agrupa muchas acciones en una sola inversión.',answer:true,
 exp:{t:'Verdadero',p:'Un ETF (Exchange Traded Fund) es como una canasta: en vez de comprar 500 acciones, compras una sola unidad que las contiene todas. Ejemplo: el S&P 500.'}},
{type:'act',icon:'fi-sr-chart-mixed-up-circle-dollar',ic:'orange',title:'Tipos de activos',
 desc:'¿Cuál de estos es un "derivado" financiero?',
 ch:[{t:'Un contrato de futuros',k:'A',ok:true},{t:'Una acción de Tesla',k:'B',ok:false},{t:'Un billete de $100',k:'C',ok:false}],
 exp:{t:'Derivados = contratos basados en otros activos',p:'Los futuros y opciones son derivados: su valor "deriva" de otro activo (acciones, petróleo, etc). BOTFX opera con estos instrumentos.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'orange',title:'Completa la frase',
 sentence:'Un ___ agrupa muchas acciones en una sola inversión. Un ___ es un contrato cuyo valor depende de otro activo.',
 blanks:['ETF','derivado'],opts:['ETF','derivado','broker','dividendo'],
 exp:{t:'ETF = canasta, Derivado = contrato',p:'Los ETFs simplifican la diversificación. Los derivados permiten estrategias avanzadas. BOTFX utiliza ambos.'}},
{type:'info',icon:'fi-sr-bulb',ic:'orange',title:'Lo que aprendiste',
 desc:'Los activos financieros son todo lo que tiene valor y puedes operar: acciones, ETFs, criptomonedas y derivados como futuros y opciones. BOTFX los analiza todos por ti.'}
]},
// ─── M2: Opciones y Contratos ───
{id:'m2',title:'Opciones y Contratos',icon:'fi-sr-document-signed',xp:45,steps:[
{type:'act',icon:'fi-sr-arrow-up-right',ic:'green',title:'¿Qué es un CALL?',
 desc:'Compraste un contrato CALL de Apple a $150. ¿Cuándo ganas dinero?',
 ch:[{t:'Cuando Apple sube por encima de $150',k:'A',ok:true},{t:'Cuando Apple baja de $150',k:'B',ok:false}],
 exp:{t:'CALL = Derecho a comprar',p:'Un CALL te da el derecho de comprar un activo a un precio fijo. Si el precio sube por encima, ganas la diferencia.'}},
{type:'act',icon:'fi-sr-arrow-down-right',ic:'orange',title:'¿Qué es un PUT?',
 desc:'Compraste un contrato PUT de Bitcoin a $60,000. ¿Cuándo ganas dinero?',
 ch:[{t:'Cuando Bitcoin sube',k:'A',ok:false},{t:'Cuando Bitcoin baja de $60,000',k:'B',ok:true}],
 exp:{t:'PUT = Derecho a vender',p:'Un PUT te da el derecho de vender a un precio fijo. Si el precio baja, ganas la diferencia. Es tu "seguro" contra caídas.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'green',title:'¿Verdadero o Falso?',
 desc:'Los contratos de futuros te obligan a comprar o vender en una fecha específica.',answer:true,
 exp:{t:'Verdadero',p:'A diferencia de las opciones (que son un derecho), los futuros son una obligación. Pero no te preocupes — BOTFX gestiona todo esto automáticamente.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'green',title:'Completa la frase',
 sentence:'Un ___ te da el derecho a comprar. Un ___ te da el derecho a vender.',
 blanks:['CALL','PUT'],opts:['CALL','PUT','STOP','BUY'],
 exp:{t:'CALL = comprar, PUT = vender',p:'Estas son las dos piezas fundamentales de las opciones. BOTFX detecta oportunidades en ambas direcciones.'}},
{type:'info',icon:'fi-sr-bulb',ic:'green',title:'Resumen',
 desc:'CALL = ganas si sube. PUT = ganas si baja. Los futuros son obligaciones, las opciones son derechos. Con BOTFX no necesitas ser experto en estos instrumentos.'}
]},
// ─── M3: Tu Cartera ───
{id:'m3',title:'Tu cartera de inversión',icon:'fi-sr-briefcase',xp:45,steps:[
{type:'act',icon:'fi-sr-briefcase',ic:'blue',title:'¿Qué es una cartera?',
 desc:'Una "cartera" de inversión es:',
 ch:[{t:'El conjunto de todos tus activos',k:'A',ok:true},{t:'Una billetera física',k:'B',ok:false},{t:'Un tipo de cuenta bancaria',k:'C',ok:false}],
 exp:{t:'Cartera = todos tus activos juntos',p:'Si tienes acciones de Apple, Bitcoin y un ETF, eso es tu cartera. La diversificación reduce tu riesgo.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'blue',title:'¿Verdadero o Falso?',
 desc:'Un dividendo es un pago que las empresas hacen a sus accionistas con parte de sus ganancias.',answer:true,
 exp:{t:'Verdadero',p:'Empresas como Coca-Cola pagan dividendos trimestrales. Es dinero que recibes solo por tener sus acciones. Ingreso pasivo real.'}},
{type:'act',icon:'fi-sr-chart-pie-alt',ic:'blue',title:'Capitalización de mercado',
 desc:'Apple vale $3 billones. Eso se llama:',
 ch:[{t:'Capitalización de mercado',k:'A',ok:true},{t:'Precio de la acción',k:'B',ok:false},{t:'Dividendo total',k:'C',ok:false}],
 exp:{t:'Market Cap = Precio × Acciones',p:'Es el valor total de una empresa en el mercado. Las empresas más grandes (Apple, Microsoft) tienen la mayor capitalización.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'blue',title:'Completa la frase',
 sentence:'La ___ de valores es donde se compran y venden acciones. La ___ de un activo es su precio actual.',
 blanks:['bolsa','cotización'],opts:['bolsa','cotización','cartera','cuenta'],
 exp:{t:'Bolsa = mercado, Cotización = precio',p:'La bolsa de valores (NYSE, NASDAQ) es el lugar. La cotización es el precio en tiempo real. BOTFX monitorea todas las bolsas.'}},
{type:'info',icon:'fi-sr-bulb',ic:'blue',title:'Lo que aprendiste',
 desc:'Tu cartera es el conjunto de tus inversiones. Los dividendos son ingresos pasivos. La capitalización mide el tamaño de una empresa. La bolsa es donde todo sucede.'}
]},
// ─── M4: Participantes ───
{id:'m4',title:'¿Quién participa?',icon:'fi-sr-users',xp:50,steps:[
{type:'act',icon:'fi-sr-user',ic:'purple',title:'¿Qué es un trader?',
 desc:'Un trader es alguien que:',
 ch:[{t:'Compra y vende activos para obtener ganancias',k:'A',ok:true},{t:'Solo invierte a largo plazo',k:'B',ok:false},{t:'Trabaja en un banco',k:'C',ok:false}],
 exp:{t:'Trader = compra y vende activamente',p:'A diferencia de un inversor pasivo, un trader busca ganancias en los movimientos de precio. Con BOTFX, tú eres el trader.'}},
{type:'act',icon:'fi-sr-building',ic:'purple',title:'¿Qué es un broker?',
 desc:'Un broker es:',
 ch:[{t:'La plataforma que conecta tu orden con el mercado',k:'A',ok:true},{t:'Un tipo de acción',k:'B',ok:false},{t:'Un impuesto del gobierno',k:'C',ok:false}],
 exp:{t:'Broker = tu puente al mercado',p:'Sin broker no puedes operar. Ejemplos: Interactive Brokers, eToro, Binance. BOTFX funciona con los mejores brokers.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'purple',title:'¿Verdadero o Falso?',
 desc:'Necesitas mínimo $10,000 para empezar a hacer trading.',answer:false,
 exp:{t:'Falso',p:'Puedes empezar desde $50-$100 dependiendo del broker. Lo importante no es cuánto tienes, sino cómo gestionas el riesgo.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'purple',title:'Completa la frase',
 sentence:'Un ___ compra y vende activos. Un ___ es la plataforma que ejecuta tus órdenes en el mercado.',
 blanks:['trader','broker'],opts:['trader','broker','banco','gobierno'],
 exp:{t:'Trader opera, Broker ejecuta',p:'Tú decides qué hacer (con ayuda de BOTFX). El broker lo ejecuta. Así funciona.'}},
{type:'info',icon:'fi-sr-bulb',ic:'purple',title:'Lo que aprendiste',
 desc:'El trader eres tú. El broker es tu plataforma. No necesitas mucho dinero para empezar. BOTFX + un buen broker = todo lo que necesitas.'}
]},
// ─── M5: Tipos de Trading ───
{id:'m5',title:'Tipos de trading',icon:'fi-sr-clock-three',xp:55,steps:[
{type:'act',icon:'fi-sr-clock-three',ic:'orange',title:'¿Qué es Day Trading?',
 desc:'Un day trader:',
 ch:[{t:'Abre y cierra operaciones en el mismo día',k:'A',ok:true},{t:'Mantiene posiciones por meses',k:'B',ok:false},{t:'Solo opera los lunes',k:'C',ok:false}],
 exp:{t:'Day Trading = abrir y cerrar en el día',p:'No dejas operaciones abiertas de noche. Reduces riesgo de gaps nocturnos. BOTFX es ideal para day trading.'}},
{type:'act',icon:'fi-sr-calendar',ic:'orange',title:'¿Qué es Swing Trading?',
 desc:'Un swing trader mantiene sus operaciones por:',
 ch:[{t:'Segundos',k:'A',ok:false},{t:'Días a semanas',k:'B',ok:true},{t:'Años',k:'C',ok:false}],
 exp:{t:'Swing = días a semanas',p:'Buscas movimientos más grandes que duran varios días. Requiere menos tiempo frente a la pantalla que el day trading.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'orange',title:'¿Verdadero o Falso?',
 desc:'El scalping busca ganar pequeñas cantidades en operaciones que duran segundos o minutos.',answer:true,
 exp:{t:'Verdadero',p:'Scalping = muchas operaciones pequeñas y rápidas. Requiere concentración extrema. BOTFX puede detectar oportunidades de scalping en tiempo real.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'orange',title:'Completa la frase',
 sentence:'El ___ abre y cierra en el mismo día. El ___ mantiene posiciones por días o semanas.',
 blanks:['day trading','swing trading'],opts:['day trading','swing trading','scalping','holding'],
 exp:{t:'Day = intradía, Swing = días/semanas',p:'Cada estilo tiene ventajas. BOTFX genera señales para ambos estilos.'}},
{type:'info',icon:'fi-sr-bulb',ic:'orange',title:'Lo que aprendiste',
 desc:'Scalping = segundos. Day trading = horas. Swing = días. Cada estilo se adapta a tu disponibilidad de tiempo. BOTFX cubre todos.'}
]},
// ─── M6: Condiciones de Mercado ───
{id:'m6',title:'Condiciones del mercado',icon:'fi-sr-chart-mixed-up-circle-dollar',xp:55,steps:[
{type:'act',icon:'fi-sr-arrow-trend-up',ic:'green',title:'Bull Market',
 desc:'Cuando los precios suben de forma sostenida, estamos en un:',
 ch:[{t:'Bull Market (mercado alcista)',k:'A',ok:true},{t:'Bear Market',k:'B',ok:false},{t:'Rango',k:'C',ok:false}],
 exp:{t:'Bull = Toro = Sube',p:'El toro ataca hacia arriba con sus cuernos. Así recuerdas: Bull Market = precios subiendo. Oportunidades de COMPRA.'}},
{type:'act',icon:'fi-sr-arrow-trend-down',ic:'orange',title:'Bear Market',
 desc:'Cuando los precios bajan de forma sostenida, estamos en un:',
 ch:[{t:'Bull Market',k:'A',ok:false},{t:'Bear Market (mercado bajista)',k:'B',ok:true},{t:'Consolidación',k:'C',ok:false}],
 exp:{t:'Bear = Oso = Baja',p:'El oso ataca hacia abajo con sus garras. Bear Market = precios bajando. Oportunidades de VENTA (short).'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'green',title:'¿Verdadero o Falso?',
 desc:'La volatilidad alta significa que el precio se mueve mucho y rápido.',answer:true,
 exp:{t:'Verdadero',p:'Alta volatilidad = grandes movimientos = más oportunidades (y más riesgo). BOTFX ajusta sus señales según la volatilidad del mercado.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'green',title:'Completa la frase',
 sentence:'Un mercado ___ es cuando los precios suben. Un mercado ___ es cuando los precios bajan.',
 blanks:['alcista','bajista'],opts:['alcista','bajista','lateral','volátil'],
 exp:{t:'Alcista = sube, Bajista = baja',p:'Identificar la tendencia es el primer paso. BOTFX lo hace automáticamente con IA.'}},
{type:'info',icon:'fi-sr-bulb',ic:'green',title:'Lo que aprendiste',
 desc:'Bull/alcista = sube. Bear/bajista = baja. Volatilidad = intensidad del movimiento. Rango = precio atrapado entre dos niveles. BOTFX lee todo esto por ti.'}
]},
// ─── M7: Análisis ───
{id:'m7',title:'Análisis del mercado',icon:'fi-sr-search-alt',xp:60,steps:[
{type:'act',icon:'fi-sr-chart-line-up',ic:'blue',title:'Análisis Técnico',
 desc:'El análisis técnico estudia:',
 ch:[{t:'Gráficas, patrones y precios pasados',k:'A',ok:true},{t:'Las noticias y reportes financieros',k:'B',ok:false},{t:'Las opiniones de expertos',k:'C',ok:false}],
 exp:{t:'Técnico = gráficas y patrones',p:'Usa gráficos para predecir movimientos futuros basándose en el pasado. BOTFX hace análisis técnico avanzado con IA.'}},
{type:'act',icon:'fi-sr-newspaper',ic:'blue',title:'Análisis Fundamental',
 desc:'El análisis fundamental estudia:',
 ch:[{t:'Solo las gráficas',k:'A',ok:false},{t:'Noticias, ganancias, economía y valor real',k:'B',ok:true},{t:'El horario del mercado',k:'C',ok:false}],
 exp:{t:'Fundamental = valor real del activo',p:'¿La empresa gana dinero? ¿La economía crece? Eso es análisis fundamental. BOTFX combina ambos tipos de análisis.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'blue',title:'¿Verdadero o Falso?',
 desc:'El análisis técnico y el fundamental se usan juntos para tomar mejores decisiones.',answer:true,
 exp:{t:'Verdadero',p:'Los mejores traders combinan ambos. El fundamental te dice QUÉ operar, el técnico te dice CUÁNDO. BOTFX los integra automáticamente.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'blue',title:'Completa la frase',
 sentence:'El análisis ___ estudia gráficas y patrones. El análisis ___ estudia noticias y valor real.',
 blanks:['técnico','fundamental'],opts:['técnico','fundamental','visual','económico'],
 exp:{t:'Técnico = gráficas, Fundamental = valor',p:'Dos enfoques, un objetivo: encontrar las mejores oportunidades. BOTFX hace ambos en tiempo real.'}},
{type:'info',icon:'fi-sr-bulb',ic:'blue',title:'Lo que aprendiste',
 desc:'Análisis técnico = leer gráficas. Análisis fundamental = leer la economía y noticias. Juntos son más poderosos. BOTFX integra ambos con inteligencia artificial.'}
]},
// ─── M8: Precio y Ejecución ───
{id:'m8',title:'Comprar, vender y ejecutar',icon:'fi-sr-exchange-alt',xp:60,steps:[
{type:'act',icon:'fi-sr-arrow-up-right',ic:'green',title:'Compra y Venta',
 desc:'En trading, una "transacción" se completa cuando:',
 ch:[{t:'Un comprador y un vendedor acuerdan un precio',k:'A',ok:true},{t:'Solo presionas comprar',k:'B',ok:false},{t:'El broker decide',k:'C',ok:false}],
 exp:{t:'Cada compra tiene una venta',p:'Para que tú compres, alguien tiene que vender. El broker conecta a ambos instantáneamente.'}},
{type:'act',icon:'fi-sr-money-bill-wave',ic:'green',title:'Ask, Bid y Mid',
 desc:'El "Ask" es $101, el "Bid" es $99. ¿Qué significan?',
 ch:[{t:'Ask = precio para comprar, Bid = precio para vender',k:'A',ok:true},{t:'Son lo mismo',k:'B',ok:false},{t:'Son comisiones del broker',k:'C',ok:false}],
 exp:{t:'Ask = compras, Bid = vendes',p:'La diferencia entre Ask y Bid se llama "spread". El Mid ($100) es el punto medio. BOTFX calcula todo esto.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'green',title:'¿Verdadero o Falso?',
 desc:'Una orden de mercado se ejecuta inmediatamente al precio actual.',answer:true,
 exp:{t:'Verdadero',p:'Orden de mercado = compras/vendes AHORA al precio disponible. Orden límite = solo se ejecuta si llega a TU precio.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'green',title:'Completa la frase',
 sentence:'El ___ es el precio al que puedes comprar. El ___ es el precio al que puedes vender.',
 blanks:['Ask','Bid'],opts:['Ask','Bid','Mid','Spread'],
 exp:{t:'Ask para comprar, Bid para vender',p:'Siempre compras un poco más caro (Ask) y vendes un poco más barato (Bid). Esa diferencia es el costo de operar.'}},
{type:'info',icon:'fi-sr-bulb',ic:'green',title:'Lo que aprendiste',
 desc:'Ask = precio de compra. Bid = precio de venta. Spread = la diferencia. Las órdenes de mercado se ejecutan al instante. BOTFX optimiza tus entradas.'}
]},
// ─── M9: Gráficas ───
{id:'m9',title:'Leer gráficas',icon:'fi-sr-chart-candlestick',xp:65,steps:[
{type:'act',icon:'fi-sr-chart-candlestick',ic:'orange',title:'¿Qué es una vela japonesa?',
 desc:'Una vela japonesa muestra:',
 ch:[{t:'Apertura, cierre, máximo y mínimo del precio',k:'A',ok:true},{t:'Solo el precio de cierre',k:'B',ok:false},{t:'El volumen de operaciones',k:'C',ok:false}],
 exp:{t:'4 datos en 1 vela',p:'Cada vela te cuenta una historia: dónde abrió, dónde cerró, hasta dónde subió y hasta dónde bajó el precio.'}},
{type:'act',icon:'fi-sr-flame',ic:'orange',title:'Vela verde vs roja',
 desc:'Una vela VERDE significa que:',
 ch:[{t:'El precio cerró MÁS ALTO de donde abrió',k:'A',ok:true},{t:'El precio bajó',k:'B',ok:false},{t:'No hubo movimiento',k:'C',ok:false}],
 exp:{t:'Verde = subió, Roja = bajó',p:'Verde/blanca = compradores ganaron. Roja/negra = vendedores ganaron. Las mechas muestran los extremos.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'orange',title:'¿Verdadero o Falso?',
 desc:'La "mecha" de una vela muestra el precio máximo y mínimo que alcanzó durante ese periodo.',answer:true,
 exp:{t:'Verdadero',p:'El cuerpo = apertura y cierre. La mecha superior = máximo. La mecha inferior = mínimo. Mechas largas = mucha lucha entre compradores y vendedores.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'orange',title:'Completa la frase',
 sentence:'El ___ mide cuántas operaciones se realizaron. Una vela ___ significa que el precio subió.',
 blanks:['volumen','verde'],opts:['volumen','verde','roja','spread'],
 exp:{t:'Volumen = actividad, Verde = subió',p:'Alto volumen confirma que el movimiento es fuerte. BOTFX analiza volumen y velas automáticamente.'}},
{type:'info',icon:'fi-sr-bulb',ic:'orange',title:'Lo que aprendiste',
 desc:'Las velas japonesas muestran 4 datos del precio. Verde = subió, Roja = bajó. Las mechas muestran extremos. El volumen confirma la fuerza del movimiento.'}
]},
// ─── M10: Niveles y Dirección ───
{id:'m10',title:'Soportes, resistencias y dirección',icon:'fi-sr-line-width',xp:65,steps:[
{type:'act',icon:'fi-sr-arrow-down',ic:'blue',title:'¿Qué es un soporte?',
 desc:'Un soporte es un nivel de precio donde:',
 ch:[{t:'El precio tiende a dejar de bajar y rebota',k:'A',ok:true},{t:'El precio siempre sube',k:'B',ok:false},{t:'No pasa nada',k:'C',ok:false}],
 exp:{t:'Soporte = piso del precio',p:'Es como un piso: el precio llega, rebota y vuelve a subir. Si rompe el soporte, puede caer mucho más.'}},
{type:'act',icon:'fi-sr-arrow-up',ic:'blue',title:'¿Qué es una resistencia?',
 desc:'Una resistencia es un nivel donde:',
 ch:[{t:'El precio tiende a dejar de subir y retrocede',k:'A',ok:true},{t:'El precio acelera',k:'B',ok:false},{t:'El mercado cierra',k:'C',ok:false}],
 exp:{t:'Resistencia = techo del precio',p:'Es como un techo: el precio llega, choca y baja. Si rompe la resistencia, puede subir con fuerza. BOTFX detecta estos niveles.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'blue',title:'¿Verdadero o Falso?',
 desc:'Ir "largo" significa que compraste esperando que el precio suba.',answer:true,
 exp:{t:'Verdadero',p:'Largo (long) = compras = ganas si sube. Corto (short) = vendes = ganas si baja. BOTFX te indica la dirección.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'blue',title:'Completa la frase',
 sentence:'Un ___ es un nivel donde el precio deja de bajar. Una ___ es donde deja de subir.',
 blanks:['soporte','resistencia'],opts:['soporte','resistencia','volumen','tendencia'],
 exp:{t:'Soporte = piso, Resistencia = techo',p:'Estos son los niveles más importantes en trading. BOTFX los identifica automáticamente con IA y GEX Bubbles.'}},
{type:'info',icon:'fi-sr-bulb',ic:'blue',title:'Lo que aprendiste',
 desc:'Soporte = piso (rebota). Resistencia = techo (retrocede). Largo = ganas si sube. Corto = ganas si baja. BOTFX detecta todos estos niveles en tiempo real.'}
]},
// ─── M11: Gestión de Riesgo ───
{id:'m11',title:'Gestión de riesgo',icon:'fi-sr-shield-check',xp:70,steps:[
{type:'act',icon:'fi-sr-shield-check',ic:'orange',title:'¿Qué es gestión de riesgo?',
 desc:'La gestión de riesgo sirve para:',
 ch:[{t:'Proteger tu capital y limitar pérdidas',k:'A',ok:true},{t:'Ganar más dinero rápido',k:'B',ok:false},{t:'Evitar pagar impuestos',k:'C',ok:false}],
 exp:{t:'Gestión de riesgo = sobrevivir',p:'El objetivo #1 no es ganar, es NO PERDER TODO. Si proteges tu capital, las ganancias llegan naturalmente.'}},
{type:'act',icon:'fi-sr-bell-ring',ic:'orange',title:'Stop Loss',
 desc:'Compraste a $100 y pones Stop Loss en $95. ¿Qué pasa si el precio baja a $90?',
 ch:[{t:'Se cierra automáticamente en $95, pierdes solo $5',k:'A',ok:true},{t:'Pierdes $10',k:'B',ok:false},{t:'No pasa nada',k:'C',ok:false}],
 exp:{t:'Stop Loss = límite automático de pérdida',p:'Sin Stop Loss, podrías perder todo. Con Stop Loss, tu pérdida máxima está controlada. BOTFX lo configura en cada señal.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'orange',title:'¿Verdadero o Falso?',
 desc:'La sobreexposición ocurre cuando arriesgas demasiado capital en una sola operación o en el mercado.',answer:true,
 exp:{t:'Verdadero',p:'Si pones todo tu dinero en una operación y pierdes, se acabó. La regla: máximo 1-2% de tu capital por operación.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'orange',title:'Completa la frase',
 sentence:'Un ___ cierra tu operación automáticamente para limitar pérdidas. El ___ es el dinero que el broker reserva para mantener tu posición abierta.',
 blanks:['Stop Loss','margen'],opts:['Stop Loss','margen','volumen','spread'],
 exp:{t:'Stop Loss protege, Margen sostiene',p:'El margen es como un depósito de garantía. Si tu pérdida supera el margen, el broker cierra tu posición (margin call).'}},
{type:'info',icon:'fi-sr-bulb',ic:'orange',title:'Lo que aprendiste',
 desc:'Gestión de riesgo = proteger tu capital. Stop Loss = tu seguro. Máximo 2% por operación. Nunca te sobreexpongas. BOTFX gestiona el riesgo automáticamente.'}
]},
// ─── M12: Estrategia y Psicología ───
{id:'m12',title:'Estrategia y disciplina',icon:'fi-sr-brain',xp:80,steps:[
{type:'act',icon:'fi-sr-chess-knight',ic:'purple',title:'¿Qué es una estrategia?',
 desc:'Una estrategia de trading es:',
 ch:[{t:'Un plan con reglas claras de cuándo comprar, vender y proteger',k:'A',ok:true},{t:'Comprar lo que todos dicen',k:'B',ok:false},{t:'Operar por intuición',k:'C',ok:false}],
 exp:{t:'Estrategia = plan con reglas',p:'Sin reglas, operas con emociones. Con reglas, operas con disciplina. BOTFX ES tu estrategia automatizada.'}},
{type:'tf',icon:'fi-sr-interrogation',ic:'purple',title:'¿Verdadero o Falso?',
 desc:'La base más simple del trading es: comprar barato y vender caro.',answer:true,
 exp:{t:'Verdadero',p:'Todo el trading se reduce a esto. La dificultad está en saber CUÁNDO está barato y cuándo caro. BOTFX resuelve eso con datos.'}},
{type:'act',icon:'fi-sr-brain',ic:'purple',title:'Disciplina',
 desc:'Después de 3 pérdidas seguidas, ¿qué deberías hacer?',
 ch:[{t:'Parar, revisar tu plan y descansar',k:'A',ok:true},{t:'Operar más para recuperar rápido',k:'B',ok:false},{t:'Doblar el tamaño de tu próxima operación',k:'C',ok:false}],
 exp:{t:'Parar y revisar = disciplina profesional',p:'El revenge trading (operar para recuperar) es la causa #1 de pérdidas grandes. Los profesionales paran. BOTFX no tiene emociones.'}},
{type:'fill',icon:'fi-sr-pencil',ic:'purple',title:'Completa la frase',
 sentence:'La ___ es seguir tu plan sin dejarte llevar por emociones. ___ significa abrir demasiadas operaciones sin justificación.',
 blanks:['disciplina','Sobre-operar'],opts:['disciplina','Sobre-operar','estrategia','analizar'],
 exp:{t:'Disciplina gana, sobre-operar destruye',p:'Los mejores traders son los más disciplinados, no los más activos. BOTFX te da señales selectivas para evitar sobre-operar.'}},
{type:'info',icon:'fi-sr-diploma',ic:'purple',title:'Has completado el ABC del Trading',
 desc:'Sabes qué son los activos, cómo funciona el mercado, cómo leer gráficas, cómo gestionar riesgo y cómo mantener la disciplina. Estás listo para operar con BOTFX.'}
]}
];
